
default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  pool: 5

development:
  <<: *default
  database: map_app_development

test:
  <<: *default
  database: map_app_test

production:
  <<: *default
  database: map_app_production
  username: map_app
  password: <%= ENV['MAP_APP_DATABASE_PASSWORD'] %>
